More installation improvements

diff --git a/mkosi.images/initrd/mkosi.extra/usr/libexec/luks-format b/mkosi.images/initrd/mkosi.extra/usr/libexec/luks-format
--- a/mkosi.images/initrd/mkosi.extra/usr/libexec/luks-format
+++ b/mkosi.images/initrd/mkosi.extra/usr/libexec/luks-format
@@ -101,44 +101,11 @@ if [ -n "${LUKSFORMAT_DETACHED_HEADER}" ]; then
   # Fall back to zero-filling the first 1GB of the device if discard fails
   blkdiscard -v -p 1G "${blkdev}" || blkdiscard -v "${blkdev}" || blkdiscard -v -z -p 16M -l 1G "${blkdev}"
 
-  wipedev="tmp-cryptwipe-${blkdev##*/}-${RANDOM}"
-
-  printf 'Writing white noise to leading 4 GiB of device %s via dm-crypt mapping %s\n' "${blkdev}" "${wipedev}"
-  # Write random junk in the leading GBs of the drive for hiding the true
-  # beginning of the encrypted data
-  cryptsetup open --type plain \
-    --key-file /dev/urandom \
-    --sector-size 4096 \
-    --cipher aes-xts-plain64 \
-    --key-size 512 \
-    "${blkdev}" \
-    "${wipedev}"
-  #time udevadm lock -d "/dev/mapper/${wipedev}" dd if=/dev/zero of="/dev/mapper/${wipedev}" bs=4M count=1024 status=progress
-  time udevadm lock -d "/dev/mapper/${wipedev}" dd if=/dev/zero of="/dev/mapper/${wipedev}" bs=4M count=32 status=progress
-
-
-  if ! cryptsetup close "${wipedev}" || cryptsetup close "${wipedev}" --debug; then
-    printf 'Failed to close cryptwipe mapping %s: %s\n' "${wipedev}" "$?"
-    printf 'Will retry...\n'
-  fi
-  if cryptsetup status "${wipedev}"; then
-    printf 'dm-crypt mapping %s is still hanging on... waiting 1 second to let udev catch up\n' "${wipedev}"
-    printf 'Some debug info:\n'
-    ls -la "/dev/mapper/${wipedev}" || true
-    lsof -w | grep -F -e "/dev/dm-" -e "${wipedev}" || true
-    sleep 1
-    if ! cryptsetup close --debug "${wipedev}"; then
-      printf 'Failed to close cryptwipe mapping %s: %s\n' "${wipedev}" "$?"
-      printf 'Falling back to deferred close\n'
-      cryptsetup close --debug --deferred "${wipedev}"
-    fi
-  fi
-
   printf 'Creating detached LUKS2 header %s\n' "${LUKSFORMAT_DETACHED_HEADER}"
   # random starting offset aligned on a 4MB boundary (SSD friendly)
-  start_offset="$(random_number_in_range 128-1024)"
-  start_offset_mb="$((start_offset * 4))"
-  # --offset must be given in 512 byte sectors.
+  start_offset_4m="$(random_number_in_range 128-1024)"
+  start_offset_mb="$((start_offset_4m * 4))"
+  # --offset must be given in 512 byte sectors, regardless of --sector-size setting.
   start_offset_blocks="$((start_offset_mb * 2048))"
 fi
 
@@ -164,6 +131,46 @@ flock -x --verbose "$0" cryptsetup luksFormat \
   ${LUKSFORMAT_INTEGRITY:+--integrity "${LUKSFORMAT_INTEGRITY}"} \
   ${start_offset_blocks:+--offset "${start_offset_blocks}"} \
   "${blkdev}"
+
+if [ -n "${LUKSFORMAT_DETACHED_HEADER}" ]; then
+  # We put noise junk data in the beginning of the device in order to hide the
+  # real start of the encrypted data.
+  # cryptsetup seems to discard all blocks on the whole device when doing
+  # luksFormat, including whatever noise we put before the data payload start
+  # offset, so we need to do this after luksFormat. This is likely just a
+  # special use case that the original developers of the luksFormat code had
+  # not considered.
+  wipedev="tmp-cryptwipe-${blkdev##*/}-${RANDOM}"
+
+  printf 'Writing white noise to leading %u MiB of device %s via dm-crypt mapping %s\n' "${start_offset_mb}" "${blkdev}" "${wipedev}"
+  # Write random junk in the leading GBs of the drive for hiding the true
+  # beginning of the encrypted data
+  cryptsetup open --type plain \
+    --key-file /dev/urandom \
+    --sector-size 4096 \
+    --cipher aes-xts-plain64 \
+    --key-size 512 \
+    "${blkdev}" \
+    "${wipedev}"
+  time udevadm lock -d "/dev/mapper/${wipedev}" dd if=/dev/zero of="/dev/mapper/${wipedev}" bs=4M count="${start_offset_4m}" status=progress
+
+  if ! cryptsetup close "${wipedev}" || cryptsetup close "${wipedev}" --debug; then
+    printf 'Failed to close cryptwipe mapping %s: %s\n' "${wipedev}" "$?"
+    printf 'Will retry...\n'
+  fi
+  if cryptsetup status "${wipedev}"; then
+    printf 'dm-crypt mapping %s is still hanging on... waiting 1 second to let udev catch up\n' "${wipedev}"
+    printf 'Some debug info:\n'
+    ls -la "/dev/mapper/${wipedev}" || true
+    lsof -w | grep -F -e "/dev/dm-" -e "${wipedev}" || true
+    sleep 1
+    if ! cryptsetup close --debug "${wipedev}"; then
+      printf 'Failed to close cryptwipe mapping %s: %s\n' "${wipedev}" "$?"
+      printf 'Falling back to deferred close\n'
+      cryptsetup close --debug --deferred "${wipedev}"
+    fi
+  fi
+fi
 
 tmp_mapping="luks-${blkdev##*/}"
 if [ -e "/dev/mapper/${tmp_mapping}" ]; then
